#!/bin/bash

# SIZE EN MB

read -r -d '' _JSON_PARTITIONS << EOM
[
    { "number": "1",
      "name": "EFI",
      "size": "512",
      "type": "ef00",
      "filesystem": "vfat",
      "mount": "/boot/efi"
    },
    { "number": "2",
      "name": "BIOS",
      "size": "1",
      "type": "ef02",
      "filesystem": "ext4",
      "mount": "none"
    },
    { "number": "3",
      "name": "SWAP",
      "size": "4096",
      "type": "8200",
      "filesystem": "swap",
      "mount": "none"
    },
    { "number": "4",
      "name": "SYSTEM",
      "size": "20480",
      "type": "8300",
      "filesystem": "ext4",
      "mount": "/"
    },
    { "number": "5",
      "name": "HOME",
      "size": "1000",
      "type": "8300",
      "filesystem": "ext4",
      "mount": "/home"
    }
]
EOM


# ============
# REQUIREMENTS
# ============

# MODULO NBD CARGADO
lsmod |grep "^nbd " >/dev/null
if ! [ $? = 0 ]
then
    modprobe nbd || :
fi


function nbd-first-free {
    local _DEVICE
    for _DEVICE in /sys/class/block/nbd*
    do
       if [ "$(cat $_DEVICE/size)" = "0" ]
       then
           echo "/dev/$(basename $_DEVICE)"
           break
       fi
    done
}

function connect_HD {
    local _TARGET="$1"
    local _DEVICE=""

    if [ -f $_TARGET ]
    then
        _DEVICE=$(nbd-first-free)
        qemu-nbd -n -c  "$_DEVICE" "$_TARGET"
        sleep 2
        if [ $? = 0 ]
        then
            echo "$_DEVICE"
        fi
    elif [ -b $_TARGET ]
    then
        echo $_TARGET
    fi

}


function disconnect_HD {
    local _DEVICE="$1"

    if [ ${_DEVICE:0:8} = "/dev/nbd" ]
    then
        sync
        sleep 2
        qemu-nbd -d "$_DEVICE" > /dev/null
    fi
}


function ls_parts {
    local _DEVICE="$1"
    lsblk -o KNAME,TYPE ${_DEVICE} | grep part | awk '{print "/dev/"$1}'
}

function disk_by_label() {
    # LABEL of FS
    local _LABEL="$1"
    local _KNAME=$( \
        lsblk -o PKNAME,TYPE,LABEL | \
        awk '$2 == "part" {print $0}' | \
        grep "$_LABEL" | \
        awk '{print $1}'
        )
    if [ -z $_KNAME ]
    then
        return 1
    else
        echo "/dev/${_KNAME}"
    fi
}

function part_by_label() {
    local _LABEL="$1"
    local _KNAME=$( \
        lsblk -o KNAME,TYPE,LABEL | \
        awk '$2 == "part" {print $0}' | \
        grep "$_LABEL" | \
        awk '{print $1}'
        )
    if [ -z $_KNAME ]
    then
        return 1
    else
        echo "/dev/${_KNAME}"
    fi
}


function shrink_HD {
    _DEVICE="$1"
    _DEVICE=$(connect_HD ${_DEVICE})
    IFS=$'\n'
    for _DEV_PART in $(ls_parts ${_DEVICE})
    do
        umount ${_DEV_PART} 2&>/dev/null || :
        shrink_part ${_DEVICE} $(id_by_part $_DEV_PART)
    done
    IFS=''
    disconnect_HD ${_DEVICE}
}


# shrink_part "/dev/loop0" "4"
function shrink_part {
    local _DEVICE="$1"
    local _NUMBER="$2"
    local _DEV_PART=$(part_by_id $_DEVICE $_NUMBER)
    local _TYPE=$(blkid -o value -s TYPE ${_DEV_PART})
    local _BLOCK=${_DEVICE:5} # eliminamos "/dev/"

    case $_TYPE in
        ext2|ext3|ext4)
            # Reducimos el FS
            e2fsck -f -y ${_DEV_PART}
            partprobe
            resize2fs -M ${_DEV_PART}   # shrink FS to minimal
            partprobe
            # Reducimos la particion
            # https://serverfault.com/questions/796758/shrink-partition-to-exactly-fit-the-underlying-filesystem-size
            local BLOCK_SIZE=$(tune2fs -l ${_DEV_PART} | grep "Block size:" |awk -F: '{print $2}')
            local BLOCK_COUNT=$(tune2fs -l ${_DEV_PART} | grep "Block count:" |awk -F: '{print $2}')
            local SECTOR_SIZE=$(cat /sys/block/${_BLOCK}/queue/hw_sector_size)
            local START_SECTOR=$(fdisk -l ${_DEVICE}|grep ${_DEV_PART} |awk '{print $2}')
            local FS_SIZE=$(($BLOCK_COUNT*$BLOCK_SIZE))
            local FS_SECTORS=$(($FS_SIZE/$SECTOR_SIZE))
            local PART_SECTORS=$(( (($FS_SECTORS-1)/2048+1)*2048 ))
            local END_SECTOR=$(( $START_SECTOR + $PART_SECTORS - 1 ))
            echo Yes | parted ---pretend-input-tty ${_DEVICE} resizepart $(echo ${_NUMBER}) ${END_SECTOR}s
            partprobe
        ;;
        *)
            echo "${_DEV_PART} TYPE: ${_TYPE} is not shrinkable"
        ;;
    esac
}


# part_uuid /dev/sda4  -> da32fdbc-0c84-4938-98b9-261cf0acbf9c
function part_uuid {
    # require util-linux package
    local _DEV_PARTITION="$1"
    echo $(blkid -s PARTUUID -o value "$_DEV_PARTITION")
}


# uuid_by_name /dev/sda SYSTEM  -> da32fdbc-0c84-4938-98b9-261cf0acbf9c
function uuid_by_name {
    local _DEVICE="$1"
    local _NAME="$2"
    part_uuid $(part_by_name ${_DEVICE} ${_NAME})
}

# uuid_by_id /dev/sda 4  -> da32fdbc-0c84-4938-98b9-261cf0acbf9c
function uuid_by_id {
    local _DEVICE="$1"
    local _NUMBER="$2"
    part_uuid $(part_by_id ${_DEVICE} ${_NUMBER})
}

function prefix_part {
    local _DEVICE="$1"
    local _PREFIX="p"
    if [ ${_DEVICE:0:7} = "/dev/sd" ]
    then
      _PREFIX=""
    fi
    echo "$_PREFIX"
}


# part_by_id /dev/nvme0n1 5   -> /dev/nvme0n1p5
function part_by_id {
    local _DEVICE="$1"
    local _NUMBER="$2"
    local _PREFIX=$(prefix_part ${_DEVICE})
    echo "${_DEVICE}${_PREFIX}${_NUMBER}"
}

# id_by_part /dev/nvme0n1p5   -> 5
function id_by_part {
    local _DEV_PART="$1"
    local _DEVICE=$(dev_by_part ${_DEV_PART})
    local _PREFIX=$(prefix_part ${_DEVICE})
    _LEN=$(( ${#_DEVICE} + ${#_PREFIX}))
    echo "${_DEV_PART:$_LEN}"
}


# dev_by_part /dev/nbd0p4   -> /dev/nbd0
function dev_by_part {
    local _DEV_PART="$1"
    local _DEVICE="/dev/$(lsblk -o KNAME,TYPE -s ${_DEV_PART}|grep disk|awk '{print $1}')"
    echo "${_DEVICE}"
}


# part_by_name /dev/sda SYSTEM   -> /dev/sda4
function part_by_name {
    local _DEVICE="$1"
    local _NAME="$2"
    local _NUMBER=$(echo "$_JSON_PARTITIONS" | jq ' .[] | select( .name == "'${_NAME}'") | .number | tonumber')
    part_by_id ${_DEVICE} ${_NUMBER}
}

# part_label /dev/sda5  -> HOME
function part_label {
    local _DEV_PART="$1"
    lsblk -n -o LABEL $_DEV_PART
}


function make_fstab {
    local _DEVICE="$1"
    local _PARTITIONS=$(echo "$_JSON_PARTITIONS"|jq -r '.[] | .number +";"+ .name +";"+ .mount +";"+ .filesystem +";" ')
    local _PARTITION
    local _NUMBER
    local _NAME
    local _MOUNT
    local _FILESYSTEM

    IFS=$'\n'
    for _PARTITION in $_PARTITIONS
    do
        _NUMBER=$(echo "$_PARTITION" | awk -F ";" '{print $1}')
        _NAME=$(echo "$_PARTITION" | awk -F ";" '{print $2}')
        _MOUNT=$(echo "$_PARTITION" | awk -F ";" '{print $3}')
        _FILESYSTEM=$(echo "$_PARTITION" | awk -F ";" '{print $4}')
        case "$_NAME" in
            "SYSTEM")
                echo "PARTUUID=$(uuid_by_id ${_DEVICE} ${_NUMBER}) $_MOUNT $_FILESYSTEM errors=remount-ro 0 1"
                ;;
            "EFI")
                echo "PARTUUID=$(uuid_by_id ${_DEVICE} ${_NUMBER}) $_MOUNT $_FILESYSTEM umask=0077 0 1"
                ;;
            "SWAP")
                echo "PARTUUID=$(uuid_by_id ${_DEVICE} ${_NUMBER}) $_MOUNT $_FILESYSTEM sw 0 0"
                ;;
            "HOME")
                echo "PARTUUID=$(uuid_by_id ${_DEVICE} ${_NUMBER}) $_MOUNT $_FILESYSTEM defaults 0 2"
                ;;
            *)
                ;;
        esac
    done
    IFS=''
}


function make_file_systems {
    local _DEVICE="$1"
    local _PARTITIONS=$(echo "$_JSON_PARTITIONS"|jq -r '.[] | .number +";"+ .name +";"+ .filesystem +";" ')
    local _PARTITION
    local _NUMBER
    local _NAME
    local _FILESYSTEM
    local _DEV_PART

    echo
    echo "Creando sistemas de ficheros"
    echo "============================"

    IFS=$'\n'
    for _PARTITION in $_PARTITIONS
    do
        _NUMBER=$(echo "$_PARTITION" | awk -F ";" '{print $1}')
        _NAME=$(echo "$_PARTITION" | awk -F ";" '{print $2}')
        _FILESYSTEM=$(echo "$_PARTITION" | awk -F ";" '{print $3}')
        _DEV_PART=$(part_by_id ${_DEVICE} ${_NUMBER})

        case "$_FILESYSTEM" in
            "ext4")
                echo "Partición $_NUMBER $_NAME -> ext4"
                umount ${_DEV_PART} 2&> /dev/null || :
                LANG=C yes |  mkfs.ext4 -E nodiscard ${_DEV_PART}
                ;;
            "swap")
                echo "Partición $_NUMBER $_NAME -> swap"
                umount ${_DEV_PART} 2&> /dev/null || :
                LANG=C yes | mkswap ${_DEV_PART} > /dev/null
                ;;
            "vfat")
                echo "Partición $_NUMBER $_NAME -> fat"
                umount ${_DEV_PART} 2&> /dev/null || :
                LANG=C yes | mkfs.fat ${_DEV_PART}> /dev/null
                ;;
            *)
                ;;
        esac

        sleep 2
        sync

    done
    IFS=''
}


function set_journal {
    local _DEVICE="$1"
    local _PARTITIONS=$(echo "$_JSON_PARTITIONS"|jq -r '.[] | .number +";"+ .name +";"+ .filesystem +";" ')
    local _PARTITION
    local _NUMBER
    local _NAME
    local _FILESYSTEM
    local _DEV_PART

    echo
    echo "Estableciendo journal"
    echo "====================="

    IFS=$'\n'
    for _PARTITION in $_PARTITIONS
    do
        _NUMBER=$(echo "$_PARTITION" | awk -F ";" '{print $1}')
        _NAME=$(echo "$_PARTITION" | awk -F ";" '{print $2}')
        _FILESYSTEM=$(echo "$_PARTITION" | awk -F ";" '{print $3}')
        _DEV_PART=$(part_by_id ${_DEVICE} ${_NUMBER})

        case "$_FILESYSTEM" in
            "ext4")
                umount ${_DEV_PART} 2&> /dev/null || :
                tune2fs -O has_journal ${_DEV_PART}
                ;;
            *)
                ;;
        esac
    done
    IFS=''
}



function get_megas_device
{
    local _DEVICE="$1"

#    local _SIZE=$(fdisk -l $_DEVICE | grep " $_DEVICE: " | cut -d ' ' -f 5)
#    _SIZE=$((_SIZE/(1024*1024)))
#    echo $_SIZE
    echo $(blockdev --getsize64 ${_DEVICE} | awk '{ printf "%.0f\n", $1/1024/1024 }')

}


function max_home_size {
    _DEVICE="$1"

    _RESERVED=$(echo "$_JSON_PARTITIONS" | jq ' .[] | select( .name != "HOME") | .size | tonumber')
    _RESERVED=$(echo 1+$_RESERVED | tr " " "+")
    _RESERVED=$(( $_RESERVED ))
    _FREE_SIZE=$(( $(get_megas_device $_DEVICE ) - $_RESERVED - 1 ))
    _HOME_SIZE=$(echo "$_JSON_PARTITIONS" | jq ' .[] | select( .name == "HOME") | .size | tonumber')

    # Limitar tamaño de la particion de datos
    if [ $_FREE_SIZE -le $_HOME_SIZE ]
    then
        echo $_FREE_SIZE
    else
        echo $_HOME_SIZE
    fi
}

# make_partitions "/dev/loop01"
function make_partitions {
    local _DEVICE="$1"
    local _GDISK=""
    local _PARTITIONS=$(echo "$_JSON_PARTITIONS"|jq -r '.[] | .number +";"+ .name +";"+ .size +";"+ .type ')
    local _PARTITION
    local _NUMBER
    local _NAME
    local _SIZE
    local _TYPE

    echo
    echo "Creating a new empty GPT partition table on $_DEVICE"
    (
    echo "o"
    echo "Y"
    echo "w"
    echo "Y"
    ) | gdisk "$_DEVICE" &>/dev/null
    check_result
    partprobe

    echo
    echo "Creando Particiones"
    IFS=$'\n'
    for _PARTITION in $_PARTITIONS
    do
        _NUMBER=$(echo "$_PARTITION" | awk -F ";" '{print $1}')
        _NAME=$(echo "$_PARTITION" | awk -F ";" '{print $2}')
        _SIZE=$(echo "$_PARTITION" | awk -F ";" '{print $3}')
        _TYPE=$(echo "$_PARTITION" | awk -F ";" '{print $4}')

        if [ $_NAME = "HOME" ]
        then
            _SIZE=$(max_home_size $_DEVICE)
        fi


        _GDISK=$(
            echo "$_GDISK";
            echo "n";
            echo "$_NUMBER";
            echo;
            echo "+${_SIZE}M";
            echo "$_TYPE";
            echo "c";
            if ! [ "$_NUMBER" = "1" ]; then echo "$_NUMBER"; fi;
            echo "$_NAME"
            )
    done
    IFS=''

    echo "o
Y$(echo "$_GDISK")
w
Y
" | gdisk ${_DEVICE}  &>/dev/null
    check_result

    partprobe
    gdisk -l ${_DEVICE}

}

function check_result {
    if [ $? = 0 ]
    then
      echo "    [OK]"
    else
      echo "    \e[31m[ERROR]\e[0m"
      sleep 5
    fi
}


function make_HD {
    local _DEVICE="$1"
    local _SIZE="$2"

    if [ -z $_SIZE ]
    then
        _SIZE=$(( 250*1024 )) # en MB
    fi

    if [ -f $_DEVICE ]
    then
        echo "Error: file $_DEVICE exists." >&2
        exit 1
    elif ! [ -b $_DEVICE ]
    then
        # lo creamos siempre en qcow2 porque falla mkfs.ext4 en vdi
        qemu-img create -f qcow2 "$_DEVICE" "${_SIZE}M"
    fi

    _DEV=$(connect_HD "$_DEVICE")
    make_partitions "$_DEV"
    disconnect_HD "$_DEV"

    _DEV=$(connect_HD "$_DEVICE")
    make_file_systems "$_DEV"
    disconnect_HD "$_DEV"

}


# clone_HD clon.qcow2 /dev/sdx
function clone_HD {
    local _SOURCE="$1"
    local _TARGET="$2"
    local _ORIGIN_TARGET=${_TARGET}
    local _PARTITIONS=$(echo "$_JSON_PARTITIONS"|jq -r '.[] | .number +";"+ .name +";"+ .size +";" ')
    local _NUMBER
    local _NAME

    make_HD "$_TARGET" ""

    _SOURCE=$(connect_HD $_SOURCE)
    _TARGET=$(connect_HD $_TARGET)

    IFS=$'\n'
    for _PARTITION in $_PARTITIONS
    do
        _NUMBER=$(echo "$_PARTITION" | awk -F ";" '{print $1}')
        _NAME=$(echo "$_PARTITION" | awk -F ";" '{print $2}')
        _SIZE=$(echo "$_PARTITION" | awk -F ";" '{print $3}')
        case "$_NAME" in
            "HOME"|"SYSTEM" )
                if [ $_NAME = "HOME" ]
                then
                    _SIZE=$(max_home_size $_TARGET)
                fi
                _DEV_PART_SOURCE=$(part_by_id $_SOURCE $_NUMBER)
                _DEV_PART_TARGET=$(part_by_id $_TARGET $_NUMBER)

                echo
                echo "Clonando: $_NAME"
                echo "================"


                mkdir -p /mnt/source
                mount -o ro -t auto ${_DEV_PART_SOURCE} /mnt/source


                mkdir -p /mnt/target
                mount -o rw,noatime,nodiratime,nodiscard -t auto ${_DEV_PART_TARGET} /mnt/target


                #rsync --info=progress2 -aHAXx /mnt/source/ /mnt/target
                rsync --info=stats2 -aHAXx /mnt/source/ /mnt/target
                #dd if=$(part_by_id $_SOURCE $_NUMBER) of=${_DEV_PART_TARGET} bs=1M oflag=direct status=progress
                sync

                umount /mnt/source 2&>/dev/null
                rmdir /mnt/source

                umount /mnt/target 2&>/dev/null
                rmdir /mnt/target

                ;;
            *)
                ;;
        esac
    done
    IFS=''
    disconnect_HD $_TARGET
    disconnect_HD $_SOURCE

    rescue $_ORIGIN_TARGET

}



# set_hostname /dev/sdc PCXXXXX
function set_hostname {
    local _DEVICE="$1"
    local _PC="$2"
    local _MOUNT="/mnt/rescue"

    _DEVICE=$(connect_HD ${_DEVICE})
    mkdir -p ${_MOUNT}
    mount -t auto $(part_by_name "${_DEVICE}" "SYSTEM" ) ${_MOUNT}

    # modificación del /etc/hosts
    echo "$_PC" > ${_MOUNT}/etc/hostname
    _FILE=${_MOUNT}/etc/azl-lan/hosts.d/10_localhost
    /bin/sed -i -e "/^127\.0\.1\.1.*$/d" $_FILE
    echo "127.0.1.1     ${_PC}.red.zaragoza.es  ${_PC}" >> $_FILE

    umount ${_MOUNT} 2&>/dev/null
    rmdir ${_MOUNT}
    disconnect_HD $_DEVICE
}


# rescue
function rescue {
    local _DEVICE="$1"
    local _MOUNT="/mnt/rescue"


    echo
    echo "GRUB"
    echo "===="

    _DEVICE=$(connect_HD ${_DEVICE})

    local _FSTAB=$(make_fstab $_DEVICE)
    local _PARTUUID=$(uuid_by_name $_DEVICE SYSTEM)
    local _DEV_SYSTEM=$(part_by_name $_DEVICE SYSTEM)

    mkdir -p ${_MOUNT}

    mount -t auto $(part_by_name "${_DEVICE}" "SYSTEM" ) ${_MOUNT}

    mkdir -p ${_MOUNT}/boot/efi
    mount -o flush -t auto $(part_by_name "${_DEVICE}" "EFI" ) ${_MOUNT}/boot/efi

    mount --bind /dev ${_MOUNT}/dev
    mount --bind /dev/pts ${_MOUNT}/dev/pts
    mount --bind /proc ${_MOUNT}/proc
    mount --bind /sys ${_MOUNT}/sys
    mount --bind /run ${_MOUNT}/run

    touch $_MOUNT/forcefsck

    # FSTAB
    # =====

    echo "$_FSTAB" > $_MOUNT/etc/fstab
    # Root partition (/) must be the first line in /etc/fstab for proper boot operation
    #awk -v puuid="$_PARTUUID" 'NR==FNR && $1 == puuid {print; next} FNR != NR' $_MOUNT/etc/fstab.tmp $_MOUNT/etc/fstab.tmp > /$_MOUNT/etc/fstab


    # Para no escanear todos los discos se deshabilita os-prober
    chroot ${_MOUNT} mv /etc/grub.d/30_os-prober /tmp/
    chroot ${_MOUNT} touch /etc/grub.d/30_os-prober

    # EFI
    #chroot ${_MOUNT} /usr/sbin/grub-install ${_DEVICE} --target=x86_64-efi --efi-directory=/boot/efi
    #chroot ${_MOUNT} /usr/sbin/update-grub
    mount -t efivarfs efivarfs ${_MOUNT}/sys/firmware/efi/efivars
    chroot ${_MOUNT} /usr/sbin/grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
    chroot ${_MOUNT} /usr/sbin/update-grub
    chroot ${_MOUNT} cp /boot/efi/EFI/grub/grubx64.efi /boot/efi/EFI/grub/BOOTX64.EFI
    chroot ${_MOUNT} cp -r /boot/efi/EFI/grub /boot/efi/EFI/BOOT # (Virtualbox)

    # BIOS
    chroot ${_MOUNT} parted ${_DEVICE} set 2 bios_grub on
    chroot ${_MOUNT} /usr/sbin/grub-install --target=i386-pc ${_DEVICE}

    # INITRAMFS
    chroot ${_MOUNT} /usr/sbin/update-initramfs -u

    # Volvemos a dejar os-prober como estaba
    chroot ${_MOUNT} mv /tmp/30_os-prober /etc/grub.d/

    umount ${_MOUNT}/sys/firmware/efi/efivars
    umount ${_MOUNT}/run 2&>/dev/null
    umount ${_MOUNT}/sys 2&>/dev/null
    umount ${_MOUNT}/proc 2&>/dev/null
    umount ${_MOUNT}/dev/pts 2&>/dev/null
    umount ${_MOUNT}/dev 2&>/dev/null


    umount ${_MOUNT}/boot/efi 2&>/dev/null
    umount ${_MOUNT} 2&>/dev/null
    rmdir ${_MOUNT}

    #set_journal $_DEVICE

    disconnect_HD $_DEVICE

}


function clone_iso {
    local _FILE_ISO="$1"
    local _DEVICE="$2"

    echo
    echo "Clone ${_FILE_ISO} -> ${_DEVICE}"
    _DEVICE=$(connect_HD ${_DEVICE})
    #wipefs --all --force ${_DEVICE}
    dd if=${_FILE_ISO} of=${_DEVICE} bs=4M status=progress
    #rsyncrsync --info=stats2 -aHAXx /mnt/source/ /mnt/target
    sync
    partprobe
    disconnect_HD ${_DEVICE}

}


function resize_MCS_DATA() {
    local LABEL="MCS_DATA"
    local PART=$(part_by_label "$LABEL")
    local DISK=$(disk_by_label "$LABEL")

    umount $PART
    parted --script --fix  $DISK resizepart 4 100%
    partprobe $DISK
    sleep 2
    e2fsck -f -p $PART
    resize2fs $PART
    mount $PART /mcsdata
}

# void free_nbd(void)
function free_nbd {
    for i in {0..15}
    do
        nbd-client -d "/dev/nbd$i"
    done
}